Repository Satellite-im/Warp, pull requests merged in 2022-12, with the labels that each got.

#102 feat: Added additional trait functions
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/direct.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
  warp/src/raygun/mod.rs
Labels: enhancement, improvement, refactoring, P-Normal

#103 feat: Added modified field to Message
  extensions/warp-rg-ipfs/Cargo.toml
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/store/direct.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
  warp/src/raygun/mod.rs
Labels: enhancement, improvement, P-Low

#87 refactor: Use "mailbox" topic approach for friend requests
  extensions/warp-mp-ipfs/examples/ipfs-friends.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
Labels: improvement, refactoring, P-Normal

#104 refactor: Store messages in the blockstore
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/config.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/conversation.rs
  extensions/warp-rg-ipfs/src/store/direct.rs
  extensions/warp-rg-ipfs/src/store/document.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
  warp/src/raygun/mod.rs
Labels: improvement, refactoring, P-Normal

#109 refactor: Split events into its own topic
  extensions/warp-rg-ipfs/src/store/message.rs
Labels: improvement, refactoring, P-High

#110 refactor: Update dependency and make changes accordingly
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-fs-ipfs/src/config.rs
  extensions/warp-fs-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
  extensions/warp-mp-ipfs/src/store/phonebook.rs
  extensions/warp-rg-ipfs/Cargo.toml
  extensions/warp-rg-ipfs/src/config.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/conversation.rs
  extensions/warp-rg-ipfs/src/store/document.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
Labels: improvement, refactoring, P-Normal

#111 feat: Added base of group chat functionality
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/config.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/conversation.rs
  extensions/warp-rg-ipfs/src/store/group.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
  warp/src/raygun/mod.rs
Labels: enhancement, P-Normal

#114 chore: Linting cleanup
  extensions/warp-pd-flatfile/src/lib.rs
  warp/src/crypto/hash.rs
  warp/src/pocket_dimension/query.rs
  warp/src/raygun/mod.rs
  warp/src/tesseract/ffi.rs
Labels: P-Low

#116 feat: Platform and Status Information
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
  warp/src/multipass/identity.rs
  warp/src/multipass/mod.rs
Labels: enhancement, improvement, P-Low

#112 refactor: Use async for multipass
  extensions/warp-fs-ipfs/examples/ipfs-example.rs
  extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
  extensions/warp-fs-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/examples/ipfs-friends.rs
  extensions/warp-mp-ipfs/examples/ipfs-identity.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/tests/accounts.rs
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  warp/src/multipass/mod.rs
Labels: improvement, refactoring, P-Low

#117 chore/multipass: Cleanup logic around platform info and status
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  warp/src/multipass/mod.rs
Labels: improvement, P-Low

#118 chore: Cleanup FFI and Interface
  extensions/warp-fs-ipfs-client/src/lib.rs
  extensions/warp-fs-ipfs/src/lib.rs
  extensions/warp-fs-memory/src/lib.rs
  extensions/warp-fs-storj/src/s3.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/lib.rs
  warp/src/constellation/mod.rs
  warp/src/multipass/mod.rs
  warp/src/raygun/mod.rs
Labels: improvement, refactoring, P-Low

#119 chore: Update dependencies
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/examples/ipfs-friends.rs
  extensions/warp-rg-ipfs/Cargo.toml
  warp/Cargo.toml
  warp/src/crypto/cipher.rs
  warp/src/crypto/mod.rs
  warp/src/error.rs
  warp/src/lib.rs
  warp/src/multipass/generator.rs
Labels: improvement, refactoring, P-Low
