Repository Satellite-im/Warp, pull requests merged in 2022-11, with the labels that each got.

#78 fix: Add checks for the profile banner and picture
  extensions/warp-mp-ipfs/src/lib.rs
Labels: improvement, P-Low

#80 fix: Trim whitespaces when checking for message length
  extensions/warp-rg-ipfs/src/store/direct.rs
Labels: bug, improvement, P-Low

#71 chore: Use strong count instead of internal counter
  warp/src/tesseract/mod.rs
Labels: improvement

#81 chore: Check and append did:key if it doesnt start with one.
  warp/src/crypto/mod.rs
Labels: improvement, P-Low

#83 refactor: Remove get_path_mut, implement Arc<RwLock<Box<T>>> for Constellation
  extensions/warp-fs-ipfs-client/src/lib.rs
  extensions/warp-fs-ipfs/src/lib.rs
  extensions/warp-fs-memory/src/native.rs
  extensions/warp-fs-storj/src/s3.rs
  warp/src/constellation/mod.rs
Labels: improvement, refactoring, P-Low

#85 feat/constellation: Add Constellation::put_stream and Constellation::get_stream
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
  extensions/warp-fs-ipfs/src/lib.rs
  warp/src/constellation/file.rs
  warp/src/constellation/item.rs
  warp/src/constellation/mod.rs
Labels: enhancement, improvement, P-Low

#89 refactor: Split friend request events
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  warp/src/multipass/mod.rs
Labels: improvement, refactoring, P-Normal

#82 feat: Implement message attachment
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
  extensions/warp-fs-ipfs/src/config.rs
  extensions/warp-fs-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/Cargo.toml
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/direct.rs
  warp/src/raygun/mod.rs
Labels: enhancement, P-Normal

#91 chore/identity: Store pictures in blocks
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
Labels: improvement, P-Low

#79 chore: Revert back to broadcasting on interval
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
Labels: improvement, P-Normal

#93 chore: Added signature to root document
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
Labels: enhancement, improvement, P-Low

#97 fix: Update ipfs dependency
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-pd-stretto/Cargo.toml
  extensions/warp-rg-ipfs/Cargo.toml
Labels: improvement

#98 Refactor: Add duplicate name error renaming item
  extensions/warp-fs-ipfs/src/lib.rs
Labels: improvement

#90 feat: Send events to conversation
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/direct.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
  warp/src/raygun/mod.rs
Labels: enhancement, P-Normal

#94 fix/request: Additional checks on incoming request
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
Labels: bug, improvement, refactoring, P-Normal

#100 refactor: Relaxes the use of locks
  extensions/warp-fs-ipfs-client/src/lib.rs
  extensions/warp-fs-ipfs/examples/ipfs-example.rs
  extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
  extensions/warp-fs-ipfs/src/lib.rs
  extensions/warp-fs-memory/src/lib.rs
  extensions/warp-fs-memory/src/native.rs
  extensions/warp-fs-storj/src/s3.rs
  extensions/warp-pd-flatfile/src/lib.rs
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/direct.rs
  warp/Cargo.toml
  warp/src/constellation/mod.rs
  warp/src/multipass/mod.rs
  warp/src/pocket_dimension/mod.rs
  warp/src/raygun/mod.rs
Labels: improvement, refactoring, P-Low
