Repository Satellite-im/Warp, pull requests merged in 2023-03, with the labels that each got.

#180 refactor: Update dependency and remove types from struct
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-fs-ipfs/examples/ipfs-example.rs
  extensions/warp-fs-ipfs/examples/ipfs-persistent.rs
  extensions/warp-fs-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/discovery.rs
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
  extensions/warp-mp-ipfs/src/store/phonebook.rs
  extensions/warp-mp-ipfs/src/store/queue.rs
  extensions/warp-rg-ipfs/Cargo.toml
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/conversation.rs
  extensions/warp-rg-ipfs/src/store/document.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
  extensions/warp-rg-ipfs/tests/direct.rs
  extensions/warp-rg-ipfs/tests/group.rs
Labels: enhancement, improvement, refactoring, P-High

#184 refactor: Split editing from RayGun::send into its own function
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/tests/direct.rs
  extensions/warp-rg-ipfs/tests/group.rs
  warp/src/raygun/mod.rs
Labels: enhancement, improvement, refactoring, P-Low

#183 feat: Add TesseractEvent
  extensions/warp-mp-ipfs/src/lib.rs
  warp/Cargo.toml
  warp/src/tesseract/mod.rs
Labels: enhancement, P-Low

#186 refactor: Change Identifier to enum and implemented Identifier::did_keys
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  warp/src/multipass/identity.rs
Labels: enhancement, improvement, refactoring, P-Low

#187 chore(typos): fix typos
  deprecated/warp-rg-libp2p/src/lib.rs
  deprecated/warp-rg-libp2p/src/solana/groupchat.rs
  extensions/readme.md
  extensions/warp-fs-ipfs/src/config.rs
  extensions/warp-fs-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/conversation.rs
  warp/build.rs
  warp/src/error.rs
  warp/src/raygun/mod.rs
Labels: documentation

#190 chore(cargo): Use workspace dependency
  Cargo.toml
  extensions/warp-fs-ipfs-client/Cargo.toml
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-fs-memory/Cargo.toml
  extensions/warp-fs-storj/Cargo.toml
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-rg-ipfs/Cargo.toml
  warp/Cargo.toml
Labels: improvement, P-Low

#192 chore: Increase transmit size
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/document.rs
Labels: improvement, P-Normal

#193 refactor: Transmit data directly rather than using encoding
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
Labels: enhancement, improvement, refactoring, P-Normal

#191 fix: Dont store images directly with own id
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
Labels: bug, improvement, P-Normal

#194 refactor: Clear images from identity
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/examples/ipfs-identity.rs
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/tests/accounts.rs
  warp/src/multipass/identity.rs
Labels: enhancement, improvement, refactoring, P-Normal

#196 chore: Format cleanup
  extensions/warp-fs-ipfs-client/src/lib.rs
  extensions/warp-fs-ipfs/examples/ipfs-example.rs
  extensions/warp-fs-ipfs/src/config.rs
  extensions/warp-fs-memory/src/lib.rs
  extensions/warp-fs-memory/src/native.rs
  extensions/warp-fs-storj/src/s3.rs
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/examples/ipfs-friends.rs
  extensions/warp-mp-ipfs/examples/ipfs-identity.rs
  extensions/warp-mp-ipfs/src/store/discovery.rs
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/phonebook.rs
  extensions/warp-mp-ipfs/src/store/queue.rs
  extensions/warp-mp-ipfs/tests/accounts.rs
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/config.rs
  extensions/warp-rg-ipfs/src/store/conversation.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
  extensions/warp-rg-ipfs/tests/direct.rs
  extensions/warp-rg-ipfs/tests/group.rs
  warp/src/constellation/item.rs
  warp/src/multipass/identity.rs
  warp/src/pocket_dimension/mod.rs
  warp/src/tesseract/mod.rs
Labels: P-Low

#197 chore: Update dependency
  Cargo.toml
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
  extensions/warp-rg-ipfs/src/store/message.rs
Labels: improvement, P-Normal

#195 feat: Add MultiPassEventKind::IdentityUpdate and emit events on updates
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/discovery.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
  warp/src/multipass/mod.rs
Labels: enhancement, improvement, P-Normal

#199 fix: Save when setting only if file doesnt exist
  warp/src/tesseract/mod.rs
Labels: bug, improvement, P-Urgent

#198 refactor: Implement Request Response for Identity Store
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/examples/ipfs-friends.rs
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/discovery.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
  extensions/warp-mp-ipfs/tests/accounts.rs
  extensions/warp-mp-ipfs/tests/friends.rs
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/tests/direct.rs
  extensions/warp-rg-ipfs/tests/group.rs
Labels: enhancement, improvement, refactoring, P-Normal

#201 add: Added UpdateKind::Misc
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  warp/src/multipass/mod.rs
Labels: improvement, P-Normal

#203 chore: Inline functions
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/lib.rs
Labels: improvement, P-Low

#204 refactor: Use relay first
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/lib.rs
Labels: improvement, refactoring, P-Low

#202 feat: Added Messages to RayGun::get_messages
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/conversation.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  warp/src/raygun/mod.rs
Labels: enhancement, P-Low

#178 feat: Implemented Keystore placeholder
  extensions/warp-rg-ipfs/src/store/keystore.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
Labels: enhancement, P-Low

#206 chore: Update configuration for event emitting, and misc
  extensions/warp-mp-ipfs/examples/identity-interface.rs
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-rg-ipfs/examples/messenger.rs
  warp/src/crypto/keypair.rs
Labels: enhancement, P-Low

#205 chore: Improvements to Discovery and PhoneBook
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/discovery.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/phonebook.rs
  extensions/warp-mp-ipfs/src/store/queue.rs
Labels: improvement, P-Low

#208 refactor: Allow attaching a file while replying
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  warp/src/raygun/mod.rs
Labels: enhancement, improvement, refactoring, P-Normal

#207 chore: Set name to group conversation
  extensions/warp-rg-ipfs/examples/messenger.rs
  extensions/warp-rg-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/src/store/conversation.rs
  extensions/warp-rg-ipfs/src/store/message.rs
  extensions/warp-rg-ipfs/src/store/mod.rs
  extensions/warp-rg-ipfs/tests/group.rs
  warp/src/raygun/mod.rs
Labels: enhancement, improvement, refactoring, P-Low

#209 fix: Enforce conversation name lengths
  extensions/warp-rg-ipfs/src/store/message.rs
Labels: bug, improvement, P-Normal

#210 chore: Update dependency
  Cargo.toml
  extensions/warp-mp-ipfs/src/lib.rs
Labels: improvement
