Repository Satellite-im/Warp, pull requests merged in 2023-02, with the labels that each got.

#157 refactor: Cleanup and return bool in MultiPass::has_friend
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
  extensions/warp-mp-ipfs/src/store/phonebook.rs
  warp/src/error.rs
  warp/src/multipass/mod.rs
Labels: improvement, refactoring, P-Normal

#162 fix: Check the boolean itself
  extensions/warp-mp-ipfs/examples/ipfs-friends.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/tests/friends.rs
Labels: bug, improvement, P-High

#158 refactor: Change IdentityUpdate to enum
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/src/lib.rs
  warp/src/multipass/identity.rs
Labels: enhancement, improvement, refactoring, P-Normal

#164 fix(Path): Fix path for different platforms
  extensions/warp-fs-ipfs/src/lib.rs
Labels: bug, improvement, P-Normal

#166 feat: Changes to Tesseract
  warp/src/error.rs
  warp/src/tesseract/mod.rs
Labels: improvement, P-Normal

#163 fix: Resolve Random Invalid Signature Error
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
Labels: bug, improvement, P-High

#168 refactor: Use Vec instead of HashSet and reenable verification
  extensions/warp-mp-ipfs/src/store/document.rs
  extensions/warp-mp-ipfs/src/store/friends.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
  extensions/warp-mp-ipfs/src/store/phonebook.rs
Labels: bug, improvement, refactoring, P-High

#170 chore/test: Update and cleanup test
  extensions/warp-mp-ipfs/tests/friends.rs
  extensions/warp-rg-ipfs/tests/group.rs
Labels: improvement, P-Low

#172 chore: Update dependency
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-rg-ipfs/Cargo.toml
Labels: improvement, P-Normal

#175 add: Implemented Steams for Cipher
  warp/Cargo.toml
  warp/src/crypto/cipher.rs
Labels: enhancement, improvement, refactoring, P-Normal

#161 add: Implemented a discovery service
  extensions/warp-mp-ipfs/src/config.rs
  extensions/warp-mp-ipfs/src/lib.rs
  extensions/warp-mp-ipfs/src/store/discovery.rs
  extensions/warp-mp-ipfs/src/store/identity.rs
  extensions/warp-mp-ipfs/src/store/mod.rs
Labels: enhancement, improvement, P-Low

#176 chore: Update dependency
  extensions/warp-fs-ipfs/Cargo.toml
  extensions/warp-mp-ipfs/Cargo.toml
  extensions/warp-rg-ipfs/Cargo.toml
Labels: improvement, P-Urgent

#177 chore: Implemented additional functions for Cipher
  extensions/warp-mp-ipfs/src/store/queue.rs
  warp/src/crypto/cipher.rs
  warp/src/tesseract/mod.rs
Labels: enhancement, improvement, refactoring, P-Low
